### ISSUE TITLE
Getting an error when calling the JSON file

### ISSUE THREAD

**Issue by Tfeinstein24** [asmaloney/Leaflet_Example#1]
Hey so I copied the way you have your json file set up and I'm getting an error that it's not proper json.  this is how I have mine set up:
`{ "markers":  [
   {
     "name": "Canada",
     "url": "https://en.wikipedia.org/wiki/Canada",
     "lat": 56.130366,
     "lng": -106.346771
   },
   {
     "name": "Anguilla",
     "url": "https://en.wikipedia.org/wiki/Anguilla",
     "lat": 18.220554,
     "lng": -63.068615
   },
   {
     "name": "Barbados",
     "url": "https://en.wikipedia.org/wiki/Barbados",
     "lat": 13.193887,
     "lng": -59.543198
   },
   {
     "name": "United States",
     "url": "https://en.wikipedia.org/wiki/United_States",
     "lat": 37.090240,
     "lng": -95.712891
   },
   {
     "name": "Ireland",
     "url": "https://en.wikipedia.org/wiki/Ireland",
     "lat": 53.412910,
     "lng": -8.243890
   },
   {
     "name": "Scotland",
     "url": "https://en.wikipedia.org/wiki/Scotland",
     "lat": 56.490671,
     "lng": -4.202646
   },
   {
     "name": "England",
     "url": "https://en.wikipedia.org/wiki/England",
     "lat": 52.355518,
     "lng": -1.174320
   },
   {
     "name": "France",
     "url": "https://en.wikipedia.org/wiki/France",
     "lat": 46.227638,
     "lng": 2.213749
   },
   {
     "name": "The Netherlands",
     "url": "https://en.wikipedia.org/wiki/The_Netherlands",
     "lat": 52.132633,
     "lng": 5.291266
   },
   {
     "name": "Switzerland",
     "url": "https://en.wikipedia.org/wiki/Switzerland",
     "lat": 46.818188,
     "lng": 8.227512
   },
   {
     "name": "South Africa",
     "url": "https://en.wikipedia.org/wiki/South_Africa",
     "lat": -30.559482,
     "lng": 22.937506
   },
   {
     "name": "Madagascar",
     "url": "https://en.wikipedia.org/wiki/Madagascar",
     "lat": -18.766947,
     "lng": 46.869107
   },
   {
     "name": "Taiwan",
     "url": "https://en.wikipedia.org/wiki/Taiwan",
     "lat": 23.697810,
     "lng": 120.960515
   },
   {
     "name": "Japan",
     "url": "https://en.wikipedia.org/wiki/Japan",
     "lat": 36.204824,
     "lng": 138.252924
   }
]}`

Any reason why the js file is unable to read my json?

**Comment by asmaloney** [comment]
According to [JSONLint](https://jsonlint.com/) this is valid JSON.

I assume the error you're getting is in the console? Can you copy-paste it here?
